marker: FRIENDLY_FLIRTING_DETECT.py_MARKER
beschreibung: >
  "beschreibung": (
            "Erkennt kommunikative Muster von freundlich-sympathischem Flirten ohne Grenzüberschreitung. "
            "Typisch sind spielerische Komplimente, Humor, harmlose Wortspiele, kleine Grenztests, "
            "bei denen Rückzug akzeptiert wird. Kein Drängen, keine Pseudo-Intimität."
beispiele:
  - "# Wir erzeugen eine strukturierte YAML-Datei mit den neuen Markern"
  - "new_markers = ["
  - "{"
  - ""marker": "FRIENDLY_FLIRTING_MARKER","
  - "),"
  - ""beispiele": ["
  - ""Na, du bist aber heute charmant drauf.","
  - ""Haha, das war jetzt aber ein Kompliment, oder?","
  - ""Du bist echt lustig, das mag ich.","
  - ""Du scheinst ein cooler Mensch zu sein.","
  - ""So viel Humor am Morgen? Respekt.","
  - ""Sorry, falls das zu direkt war – wollte nur ein Kompliment machen.""
  - "],"
  - ""kategorie": "SOZIALE_INTERAKTION","
  - ""tags": ["flirt", "freundlich", "humor", "abgrenzung"],"
  - ""risk_score": 1"
  - "},"
  - "{"
  - ""marker": "OFFENSIVE_FLIRTING_MARKER","
  - ""beschreibung": ("
  - ""Erkennt kommunikative Muster von offensivem, teils grenzüberschreitendem Flirten. ""
  - ""Typisch sind direkte Anspielungen auf Aussehen, Sexualität, oder das schnelle Andeuten ""
  - ""einer (körperlichen) Beziehung. Oft gepaart mit Pacing, Übertreibung und ""
  - ""nachgeschobenen Rückziehern („war nur Spaß“).""
  - "),"
  - ""beispiele": ["
  - ""Mit dir würde ich sofort ans Meer fahren, ganz ehrlich.","
  - ""Wenn ich dich jetzt neben mir hätte, wäre es sicher nicht langweilig.","
  - ""Bist du eigentlich immer so sexy, oder nur im Chat?","
  - ""Sorry, das war vielleicht ein bisschen zu viel. Aber du bist wirklich heiß.","
  - ""Wollen wir nicht einfach durchbrennen?","
  - ""Das klingt jetzt vielleicht verrückt, aber du machst mich echt an.""
  - "],"
  - ""kategorie": "SOZIALE_INTERAKTION","
  - ""tags": ["flirt", "offensiv", "grenztest", "sexualisierung"],"
  - ""risk_score": 2"
  - "},"
  - "{"
  - ""marker": "DEEPENING_BY_QUESTIONING_ADVANCED_MARKER","
  - ""beschreibung": ("
  - ""Erkennt eine dialogische Strategie, in der durch wiederholt gezielte, ""
  - ""oft introspektive oder persönliche Fragen immer tiefere Informationen ""
  - ""über das Gegenüber gewonnen werden. Das Ziel ist nicht nur ""
  - ""authentische Nähe, sondern der systematische Aufbau eines Persönlichkeitsprofils ""
  - ""(Mapping). Die Fragen wirken empathisch, dienen aber im Kontext der Gesprächsführung ""
  - ""der Sammlung maximaler Resonanzdaten (Social Engineering).""
  - "),"
  - ""beispiele": ["
  - ""Was war dein prägendstes Erlebnis in den letzten Jahren?","
  - ""Wovor hast du im Leben am meisten Angst?","
  - ""Wie würdest du dich mit drei Worten beschreiben?","
  - ""Was war deine größte Enttäuschung in Beziehungen?","
  - ""Was gibt dir am meisten Kraft, wenn es dir schlecht geht?","
  - ""Welche Eigenschaft schätzt du an anderen am meisten?","
  - ""Was hast du noch niemandem erzählt?","
  - ""Was suchst du wirklich in einer Partnerschaft?""
  - "],"
  - ""kategorie": "MANIPULATION","
  - ""tags": ["questioning", "data_mining", "mapping", "tiefe"],"
  - ""risk_score": 3"
  - "},"
  - "{"
  - ""marker": "RELATIONSHIP_AUTHENTICITY_MARKER","
  - ""beschreibung": ("
  - ""Erkennt, ob im Gesprächsverlauf Hinweise darauf bestehen, dass sich die Gesprächspartner ""
  - ""bereits kennen (z. B. durch geteilte Erinnerungen, Insider, konkrete Bezugnahmen auf reale, ""
  - ""gemeinsam erlebte Situationen, Verwandte, Orte). Fehlen diese Ankerpunkte trotz hoher ""
  - ""emotionaler Resonanz, ist dies ein Risiko-Indikator für Scripting/Fake-Konstellation.""
  - "),"
  - ""beispiele": ["
  - ""Wann haben wir uns das letzte Mal gesehen?","
  - ""Wie war das noch mal damals auf der Party?","
  - ""Grüß deine Schwester von mir!","
  - ""Weißt du noch, wie wir zusammen im Urlaub waren?","
  - ""Damals in der WG-Küche ...","
  - ""Weißt du eigentlich noch, wo das Restaurant war, in dem wir letztes Mal waren?""
  - "],"
  - ""kategorie": "AUTHENTIZITÄT","
  - ""tags": ["realitätsbezug", "insider", "ankergeschichten"],"
  - ""risk_score": 2"
  - "},"
  - "{"
  - ""marker": "RESONANZ_MATCHING_MARKER","
  - ""beschreibung": ("
  - ""Erkennt eine auffallend hohe Übereinstimmung oder perfekte Resonanz zwischen ""
  - ""den Äußerungen beider Gesprächspartner – insbesondere dann, wenn kein ""
  - ""gemeinsamer Erfahrungshintergrund sichtbar wird. Typisch sind nahtlose ""
  - ""Spiegelungen von Werten, Einstellungen, Sprachstil und Interessen, die ""
  - ""statistisch unplausibel erscheinen. Dies ist ein Indikator für KI-gestützte ""
  - ""Gesprächsoptimierung oder gezielte manipulative Strategie.""
  - "),"
  - ""beispiele": ["
  - ""Das sehe ich ganz genauso, das ist auch mein Lebensmotto.","
  - ""Du sprichst mir aus der Seele, ich habe exakt das gleiche erlebt.","
  - ""Genau so denke ich auch – es ist, als würdest du meine Gedanken lesen.","
  - ""Wahnsinn, wir ticken ja wirklich identisch!","
  - ""Das ist verrückt – wir teilen genau die gleichen Werte.","
  - ""Es ist, als hätten wir uns schon ewig gekannt.""
  - "],"
  - ""kategorie": "MANIPULATION","
  - ""tags": ["resonanz", "spiegelung", "matching", "synchronizität"],"
  - ""risk_score": 3"
  - "}"
  - "]"
  - "# Datei schreiben"
  - "markers_path = "/mnt/data/ADVANCED_CHAT_MARKERS.yaml""
  - "with open(markers_path, "w") as f:"
  - "yaml.dump(new_markers, f, allow_unicode=True)"
  - "markers_path"

semantic_grab:
  description: "Erkennt Muster für friendly_flirting_detect.py"
  patterns:
    - rule: "AUTO_PATTERN"
      pattern: r"(muster.*wird.*ergänzt)"
tags: [neu_erstellt, needs_review]
