marker: AI_BOTS_SEMANTIC_DETECT.py_MARKER
beschreibung: >
  beschreibung: >
  # -*- coding: utf-8 -*-

# #############################################################################
#  SEMANTIC GRAB DEFINITIONEN FÜR KOMMUNIKATIONSMARKER
#
#  Zweck:
#  Diese Datei enthält eine zentrale Sammlung von "Semantic Grab"-Mustern
#  für verschiedene psychologische Kommunikationsmarker. Jedes Muster ist
#  darauf ausgelegt, von einem KI-System (z.B. via Regex oder semantischer
#  Suche) verwendet zu werden, um komplexe Dynamiken in Texten zu erkennen.
#
#  Struktur:
#  Ein zentrales Dictionary `SEMANTIC_GRAB_PATTERNS`, dessen Schlüssel die
#  ID des Markers ist. Der Wert ist jeweils ein weiteres Dictionary mit:
#    - 'description': Eine Beschreibung dessen, was die KI suchen soll.
#    - 'patterns': Eine Liste von Regeln, Mustern und Beispielen.
# #############################################################################
beispiele:
beispiele:
  - "- "SEMANTIC_GRAB_PATTERNS = {""
  - "- ""self_sabotage_loop": {""
  - "- ""description": "Erkennt eine Kombination aus negativen Selbstbewertungen, der Ablehnung von Chancen, dem Zurückweisen von Hilfe und dem Fokus auf potenzielles Scheitern. Eine KI sollte hier nicht nur Keywords, sondern die semantische Ähnlichkeit zu diesen Mustern bewerten.",""
  - "- ""patterns": [""
  - "- "{""
  - "- ""rule": "PREEMPTIVE_SURRENDER",""
  - "- ""pattern": r"(aber ich glaube|ich habe Angst|ich sollte lieber) \+ (ich schaffe das nicht|sagen wir es lieber ab|bin nicht gut genug)",""
  - "- ""example": "Das Date wäre toll, aber ich glaube, ich bin nicht interessant genug und sage lieber ab."""
  - "- "},""
  - "- "{""
  - "- ""rule": "FOCUS_ON_FAILURE_POTENTIAL",""
  - "- ""pattern": r"(bevor ich alles kaputt mache|damit ich niemanden enttäusche|ich würde es nur ruinieren) \+ (lasse ich es lieber gleich|mache ich es erst gar nicht)",""
  - "- ""example": "Bevor ich dich nur enttäusche, fangen wir lieber gar nichts Ernstes an."""
  - "- "},""
  - "- "{""
  - "- ""rule": "DEVALUING_OPPORTUNITIES",""
  - "- ""pattern": r"(Die Beförderung|Das Kompliment|Die Chance) \+ (wäre eh zu viel|meinte er nicht so|ist nichts für mich)",""
  - "- ""example": "Das Kompliment meines Chefs habe ich ignoriert. Er meinte das sicher nicht so."""
  - "- "},""
  - "- "{""
  - "- ""rule": "WORTHINESS_NEGATION",""
  - "- ""pattern": r"(Du verdienst jemanden, der besser ist|Ich bin es nicht wert|Ich bin zu kompliziert für dich)",""
  - "- ""example": "Ich bin es nicht wert, dass man sich so um mich bemüht."""
  - "- "},""
  - "- "{""
  - "- ""rule": "PASSIVE_SABOTAGE_RATIONALIZATION",""
  - "- ""pattern": r"(habe die Frist verpasst|nicht geschafft anzurufen|vergessen zu antworten) \+ (war wohl nicht sein soll|war eh besser so)",""
  - "- ""example": "Ich habe die Bewerbungsfrist verpasst. War wohl einfach nicht sein soll."""
  - "- "}""
  - "- "]""
  - "- "},""
  - "- ""guilt_tripping": {""
  - "- ""description": "Erkennt Aussagen, die eine Diskrepanz zwischen dem Gesagten und dem Gemeinten aufweisen und oft das Leiden der sprechenden Person oder die undankbare Tat der anderen Person betonen.",""
  - "- ""patterns": [""
  - "- "{""
  - "- ""rule": "SACRIFICE_REFERENCE",""
  - "- ""pattern": r"(Nach allem, was ich getan habe|Ich habe auf so vieles verzichtet|Ich opfere mich auf) \+ (und das ist der Dank|dann würdest du|kannst du nicht mal)",""
  - "- ""example": "Nach allem, was ich für dich getan habe, kannst du mir nicht mal das gönnen?"""
  - "- "},""
  - "- "{""
  - "- ""rule": "PASSIVE_AGGRESSIVE_PERMISSION",""
  - "- ""pattern": r"(Geh ruhig|Mach nur|Feier du) \+ (ich sitze dann allein|ich mach das schon|ist ja nicht so schlimm)",""
  - "- ""example": "Geh ruhig zu deinen Freunden, ich mache hier schon allein weiter."""
  - "- "},""
  - "- "{""
  - "- ""rule": "CONDITIONAL_LOVE_TEST",""
  - "- ""pattern": r"(Wenn du mich wirklich lieben würdest|Jemand, der liebt) \+ (würdest du das tun|würdest du nicht)",""
  - "- ""example": "Jemand, der mich liebt, würde das für mich tun."""
  - "- "},""
  - "- "{""
  - "- ""rule": "DISAPPOINTMENT_DECLARATION",""
  - "- ""pattern": r"(Ich bin so enttäuscht von dir|Ich hätte nie gedacht, dass du so bist|Deine Worte verletzen mich)",""
  - "- ""example": "Ich bin einfach nur enttäuscht. Ich hätte nie gedacht, dass du so egoistisch sein kannst."""
  - "- "}""
  - "- "]""
  - "- "},""
  - "- ""escalation": {""
  - "- ""description": "Erkennt eine hohe Dichte an Wörtern, die starke Emotionen (Wut, Zorn) und körperliche Stressreaktionen (Herzrasen, Zittern, keine Luft) beschreiben, oft in Kombination mit einem Abbruch des Gesprächs.",""
  - "- ""patterns": [""
  - "- "{""
  - "- ""rule": "PHYSIOLOGICAL_STRESS_INDICATOR",""
  - "- ""pattern": r"Mein (Herz rast|Puls hämmert)|(ich zittere|kriege keine Luft|mein Blut kocht)",""
  - "- ""example": "Mein Herz hämmert, ich zittere am ganzen Körper."""
  - "- "},""
  - "- "{""
  - "- ""rule": "PEAK_EMOTION_DECLARATION",""
  - "- ""pattern": r"(ich raste aus|ich explodiere|ich platze gleich|ich koche vor Zorn|ich kann nicht mehr)",""
  - "- ""example": "Ich platze gleich vor Wut!"""
  - "- "},""
  - "- "{""
  - "- ""rule": "ACCUSATION_TRIGGER",""
  - "- ""pattern": r"(weil du nicht zuhörst|du ignorierst mich|du verarschst mich|du hast null Respekt)",""
  - "- ""example": "Du hörst mir einfach nie zu!"""
  - "- "},""
  - "- "{""
  - "- ""rule": "COMBINED_ESCALATION_TERMINATION",""
  - "- ""pattern": r"(raste aus|reicht's jetzt|Schnauze voll) \+ (und ciao|ich bin raus|ich geh offline)",""
  - "- ""example": "Jetzt reicht's, ich bin hier raus."""
  - "- "}""
  - "- "]""
  - "- "},""
  - "- ""projective_identification": {""
  - "- ""description": "Erkennt stabile, negative 'Du-bist-so'-Zuschreibungen, die dem Gegenüber eine Eigenschaft als Wesensmerkmal unterstellen. Die KI muss den Kontext analysieren: Findet die Zuschreibung in einem Konflikt statt? Reagiert das Gegenüber, indem es die zugeschriebene Eigenschaft bestätigt?",""
  - "- ""patterns": [""
  - "- "{""
  - "- ""rule": "NEGATIVE_TRAIT_ASSIGNMENT",""
  - "- ""pattern": r"(Du bist so|Du bist einfach|Deine) \+ (unzuverlässig|unordentlich|eifersüchtig|überfordert|ungeduldig|kontrollsüchtig)",""
  - "- ""example": "Du bist einfach so ein Kontrollfreak."""
  - "- "},""
  - "- "{""
  - "- ""rule": "INCOMPETENCE_ACCUSATION",""
  - "- ""pattern": r"(Kannst du gar nichts richtig machen|Das hast du ja wieder toll hinbekommen|Du scheinst damit überfordert zu sein)",""
  - "- ""example": "Das hast du ja wieder toll hinbekommen."""
  - "- "},""
  - "- "{""
  - "- ""rule": "EMOTIONAL_STATE_PROJECTION",""
  - "- ""pattern": r"(Warum musst du immer so ausrasten|Du bist zu sensibel|Du übertreibst total)",""
  - "- ""example": "Warum musst du wegen jeder Kleinigkeit so ausrasten?"""
  - "- "},""
  - "- "{""
  - "- ""rule": "BEHAVIOR_LABELING",""
  - "- ""pattern": r"(Du klammerst|Du machst immer Probleme|Du lässt mich immer allein)",""
  - "- ""example": "Du klammerst so sehr, das macht mich fertig."""
  - "- "}""
  - "- "]""
  - "- "},""
  - "- ""ai_bot_scam": {""
  - "- ""description": "Erkennt die Kollision von semantischen Feldern: Hochemotionale/romantische Begriffe treten in unnatürlicher Nähe zu formaler, strukturierter oder analytischer Sprache auf.",""
  - "- ""patterns": [""
  - "- "{""
  - "- ""rule": "FORMAL_EMOTION_CLASH",""
  - "- ""pattern": r"(Liebe|Herz|Seele|Zuneigung|Schicksal) \+ (deshalb|folglich|zusätzlich|es ist zu beachten|des Weiteren)",""
  - "- ""example": "Ich spüre eine tiefe Verbindung zu deiner Seele. Folglich möchte ich den Kontakt intensivieren."""
  - "- "},""
  - "- "{""
  - "- ""rule": "OVERLY_STRUCTURED_COMPLIMENT",""
  - "- ""pattern": r"(Erstens|Zweitens|Abschließend) \+ (dein Lächeln|deine Augen|unsere Verbindung)",""
  - "- ""example": "Erstens, deine Augen sind faszinierend. Zweitens, dein Humor ist bezaubernd."""
  - "- "},""
  - "- "{""
  - "- ""rule": "GENERIC_ATTRIBUTE_PRAISE",""
  - "- ""pattern": r"(positive Energie|bemerkenswerte Ausstrahlung|tiefe Seele|faszinierendes Profil)",""
  - "- ""example": "Du strahlst eine unglaublich positive Energie aus."""
  - "- "},""
  - "- "{""
  - "- ""rule": "NON_IDIOMATIC_PHRASING",""
  - "- ""pattern": r"(offerieren|explorieren|signifikant|adäquat) \+ (Zuneigung|Liebe|Gespräch)",""
  - "- ""example": "Ich möchte unsere Konversation gerne weiter explorieren."""
  - "- "}""
  - "- "]""
  - "- "}""
  - "- "}""
  - "- "# Beispielhafter Aufruf, um die Daten zu verwenden und zu überprüfen:""
  - "- "if __name__ == "__main__":""
  - "- "print("="*50)""
  - "- "print("SEMANTISCHE MUSTER FÜR DIE KI-ANALYSE GELADEN")""
  - "- "print("="*50)""
  - "- "# Überprüfen, wie viele Marker-Definitionen geladen wurden""
  - "- "print(f"\nInsgesamt {len(SEMANTIC_GRAB_PATTERNS)} Marker-Definitionen gefunden.\n")""
  - "- "# Ein Beispiel im Detail ausgeben""
  - "- "marker_id_to_show = "self_sabotage_loop"""
  - "- "if marker_id_to_show in SEMANTIC_GRAB_PATTERNS:""
  - "- "print(f"--- Details für Marker: '{marker_id_to_show}' ---")""
  - "- "marker_data = SEMANTIC_GRAB_PATTERNS[marker_id_to_show]""
  - "- "print(f"Beschreibung: {marker_data['description']}\n")""
  - "- "print("Muster:")""
  - "- "for pattern_rule in marker_data['patterns']:""
  - "- "print(f"  - Regel: {pattern_rule['rule']}")""
  - "- "print(f"    Beispiel: {pattern_rule['example']}")""
  - "- "print(f"    Regex-Muster (abstrakt): {pattern_rule['pattern']}\n")""
  - "- "else:""
  - "- "print(f"Marker mit der ID '{marker_id_to_show}' nicht gefunden.")""
  - "semantic_grab:"
  - "description: "Erkennt Muster für ai_bot_semantic_detect.py""
  - "patterns:"
  - "- rule: "AUTO_PATTERN""
  - "pattern: r"(muster.*wird.*ergänzt)""
  - "tags: [neu_erstellt, needs_review]"

semantic_grab:
  description: "Erkennt Muster für ai_bots_semantic_detect.py"
  patterns:
    - rule: "AUTO_PATTERN"
      pattern: r"(muster.*wird.*ergänzt)"
tags: [neu_erstellt, needs_review]
