marker: PROJECTIVE_IDENTIFICATION_SEMANTIC_DETECTIO.py_MARKER
beschreibung: >
  # -*- coding: utf-8 -*-

# #############################################################################
#  STRUKTURIERTE DEFINITIONEN PSYCHOLOGISCHER KOMMUNIKATIONSMARKER
#
#  Zweck:
#  Diese Datei enthält eine Liste von detailliert definierten Markern für die
#  semantische Analyse von Kommunikation. Jeder Marker ist als Python-Dictionary
#  strukturiert und enthält:
#    - Beschreibung und typische Szenarien
#    - Realistische Beispiele
#    - Mögliche Kombinationen zu Meta-Markern
#    - "Semantic Grab": Konkrete Muster für die KI-Erkennung
#    - Psychologischen Hintergrund zur theoretischen Verankerung
#
#  Diese Struktur ist darauf ausgelegt, von KI-Systemen, insbesondere
#  NLP-Modellen, verarbeitet zu werden, um tiefere Einblicke in
#  Gesprächsdynamiken zu gewinnen.
# #############################################################################
beispiele:
  - "STRUKTURIERTE_MARKER_DEFINITIONEN = ["
  - "{"
  - ""id": "self_sabotage_loop","
  - ""name": "SELF_SABOTAGE_LOOP_MARKER","
  - ""beschreibung": "Ein Verhaltens- oder Kommunikationsmuster, bei dem eine Person ihre eigenen Chancen auf Erfolg, Nähe oder eine positive Problemlösung aktiv oder passiv untergräbt.","
  - ""szenarien": ["
  - ""Dating & Beziehungsanbahnung (z.B. Absagen von Verabredungen)","
  - ""Berufsleben & Karriere (z.B. Ablehnen von Beförderungen, Verpassen von Fristen)","
  - ""Konfliktlösung (z.B. Gesprächsabbruch aus Angst, alles schlimmer zu machen)","
  - ""Therapie- oder Coaching-Prozesse""
  - "],"
  - ""dynamik": "Die treibende Kraft ist eine tiefsitzende Angst (z.B. vor Versagen, Ablehnung, Intimität), die durch die Selbstsabotage 'kontrolliert' werden soll. Es ist eine dysfunktionale Schutzstrategie nach dem Motto: 'Wenn ich es selbst zerstöre, kontrolliere ich den Schmerz und die Enttäuschung'. Dies führt zu einer sich selbst erfüllenden Prophezeiung.","
  - ""beispiele": ["
  - ""Beziehung/Dating: 'Du verdienst jemanden, der besser für dich ist als ich.'","
  - ""Beruf: 'Ach, die Beförderung sollen sie jemand anderem geben. Der Druck wäre mir eh zu groß.'","
  - ""Konflikt: 'Lass uns das Thema beenden, ich mache doch eh alles nur noch schlimmer.'","
  - ""Hilfe ablehnen: 'Nein, danke für die Hilfe. Ich will dir keine Umstände machen.'","
  - ""Passive Sabotage: 'Ich habe die Bewerbungsfrist verpasst. War wohl einfach nicht sein soll.'","
  - ""Proaktive Sabotage: 'Ich habe das Projekt absichtlich nicht perfekt gemacht, damit die Erwartungen beim nächsten Mal nicht so hoch sind.'","
  - ""Digitale Variante (Chat): 'Ich antworte ihm extra nicht, dann merkt er vielleicht von selbst, dass ich zu kompliziert bin.'""
  - "],"
  - ""metamarker_kombinationen": ["
  - "{"
  - ""name": "Destruktive Hilflosigkeit","
  - ""kombination_mit": "Emotionaler Rückzugsdruck","
  - ""szenario": "Die Selbstsabotage wird zur Waffe. Beispiel: 'Ich weiß, ich kriege das Projekt nicht hin. Ich ziehe mich zurück, bevor ich alles ruiniere. Dir scheint das ja ohnehin egal zu sein.'""
  - "},"
  - "{"
  - ""name": "Proaktive Resignation","
  - ""kombination_mit": "PLAYING_VICTIM_MARKER","
  - ""szenario": "Die Selbstsabotage wird als unabwendbares Schicksal dargestellt, das Mitleid erregen soll. Beispiel: 'Ich fange mit der Diät lieber erst gar nicht an, ich halte das eh nicht durch. Bei mir scheitert ja sowieso immer alles, egal was ich versuche.'""
  - "}"
  - "],"
  - ""semantic_grab": {"
  - ""description": "Erkennt eine Kombination aus negativen Selbstbewertungen, der Ablehnung von Chancen, dem Zurückweisen von Hilfe und dem Fokus auf potenzielles Scheitern. Eine KI sollte hier nicht nur Keywords, sondern die semantische Ähnlichkeit zu diesen Mustern bewerten.","
  - ""patterns": ["
  - "{"
  - ""rule": "PREEMPTIVE_SURRENDER","
  - ""pattern": "(aber ich glaube|ich habe Angst|ich sollte lieber) + (ich schaffe das nicht|sagen wir es lieber ab|bin nicht gut genug)","
  - ""example": "Das Date wäre toll, aber ich glaube, ich bin nicht interessant genug und sage lieber ab.""
  - "},"
  - "{"
  - ""rule": "FOCUS_ON_FAILURE_POTENTIAL","
  - ""pattern": "(bevor ich alles kaputt mache|damit ich niemanden enttäusche|ich würde es nur ruinieren) + (lasse ich es lieber gleich|mache ich es erst gar nicht)","
  - ""example": "Bevor ich dich nur enttäusche, fangen wir lieber gar nichts Ernstes an.""
  - "},"
  - "{"
  - ""rule": "DEVALUING_OPPORTUNITIES","
  - ""pattern": "(Die Beförderung|Das Kompliment|Die Chance) + (wäre eh zu viel|meinte er nicht so|ist nichts für mich)","
  - ""example": "Das Kompliment meines Chefs habe ich ignoriert. Er meinte das sicher nicht so.""
  - "},"
  - "{"
  - ""rule": "WORTHINESS_NEGATION","
  - ""pattern": "(Du verdienst jemanden, der besser ist|Ich bin es nicht wert|Ich bin zu kompliziert für dich)","
  - ""example": "Ich bin es nicht wert, dass man sich so um mich bemüht.""
  - "},"
  - "{"
  - ""rule": "PASSIVE_SABOTAGE_RATIONALIZATION","
  - ""pattern": "(habe die Frist verpasst|nicht geschafft anzurufen|vergessen zu antworten) + (war wohl nicht sein soll|war eh besser so)","
  - ""example": "Ich habe die Bewerbungsfrist verpasst. War wohl einfach nicht sein soll.""
  - "}"
  - "]"
  - "},"
  - ""psychologischer_hintergrund": ["
  - "{"theorie": "Schematherapie (z.B. Schema 'Versagen' oder 'Unzulänglichkeit')"},"
  - "{"theorie": "Bindungstheorie (oft bei desorganisiertem oder vermeidendem Bindungsstil)"},"
  - "{"abwehrmechanismus": "Agieren (das Ausleben eines unbewussten Konflikts), Regression"}"
  - "]"
  - "},"
  - "{"
  - ""id": "guilt_tripping","
  - ""name": "GUILT_TRIPPING_MARKER (Schuldinduktion)","
  - ""beschreibung": "Die manipulative Taktik, bei einer anderen Person gezielt Schuldgefühle zu erzeugen, um sie zu einem bestimmten Verhalten zu bewegen. Dies geschieht durch offene oder subtile Vorwürfe, Appelle an Pflichtgefühl oder die Betonung des eigenen Leidens.","
  - ""szenarien": ["
  - ""Familiäre Konflikte","
  - ""Paarbeziehungen","
  - ""Arbeitsumfeld (z.B. bei der Verteilung von Aufgaben)""
  - "],"
  - ""dynamik": "Die 'Formel' lautet oft: Appell an Pflicht/Liebe + Implizite Androhung von emotionalem Entzug + Erzeugung von Schuldgefühlen. Der andere soll sich moralisch verpflichtet fühlen, den Wünschen des Manipulators zu entsprechen.","
  - ""beispiele": ["
  - ""Passiv-aggressiv: 'Schon gut, feier du deinen Geburtstag groß. Ich sitze dann halt an dem Tag allein zu Hause, macht nichts.'","
  - ""Offener Vorwurf: 'Nach all den Jahren, die ich für diese Firma geopfert habe, kannst du mir nicht mal diesen einen freien Tag gönnen?'","
  - ""Liebe an Bedingungen knüpfen: 'Wenn du mich wirklich lieben würdest, würdest du mich heute nicht allein lassen wollen, wo ich so einen schweren Tag hatte.'","
  - ""Versteckter Appell: 'Du musst mir nicht helfen. Ich will ja nicht, dass du dich meinetwegen zu etwas gezwungen fühlst.'","
  - ""Bezug auf Dritte: 'Dein Vater wäre sehr traurig, wenn er sehen würde, wie du mit mir umgehst.'""
  - "],"
  - ""metamarker_kombinationen": [],"
  - ""semantic_grab": {"
  - ""description": "Erkennt Aussagen, die eine Diskrepanz zwischen dem Gesagten und dem Gemeinten aufweisen und oft das Leiden der sprechenden Person oder die undankbare Tat der anderen Person betonen.","
  - ""patterns": ["
  - "{"
  - ""rule": "SACRIFICE_REFERENCE","
  - ""pattern": "(Nach allem, was ich getan habe|Ich habe auf so vieles verzichtet|Ich opfere mich auf) + (und das ist der Dank|dann würdest du|kannst du nicht mal)","
  - ""example": "Nach allem, was ich für dich getan habe, kannst du mir nicht mal das gönnen?""
  - "},"
  - "{"
  - ""rule": "PASSIVE_AGGRESSIVE_PERMISSION","
  - ""pattern": "(Geh ruhig|Mach nur|Feier du) + (ich sitze dann allein|ich mach das schon|ist ja nicht so schlimm)","
  - ""example": "Geh ruhig zu deinen Freunden, ich mache hier schon allein weiter.""
  - "},"
  - "{"
  - ""rule": "CONDITIONAL_LOVE_TEST","
  - ""pattern": "(Wenn du mich wirklich lieben würdest|Jemand, der liebt) + (würdest du das tun|würdest du nicht)","
  - ""example": "Jemand, der mich liebt, würde das für mich tun.""
  - "},"
  - "{"
  - ""rule": "DISAPPOINTMENT_DECLARATION","
  - ""pattern": "(Ich bin so enttäuscht von dir|Ich hätte nie gedacht, dass du so bist|Deine Worte verletzen mich)","
  - ""example": "Ich bin einfach nur enttäuscht. Ich hätte nie gedacht, dass du so egoistisch sein kannst.""
  - "}"
  - "]"
  - "},"
  - ""psychologischer_hintergrund": ["
  - "{"theorie": "Transaktionsanalyse"},"
  - "{"abwehrmechanismus": "Projektion, Externalisierung"}"
  - "]"
  - "},"
  - "{"
  - ""id": "escalation","
  - ""name": "ESCALATION_MARKER","
  - ""beschreibung": "Ein plötzlicher, intensiver Anstieg der emotionalen und/oder physiologischen Erregung, der oft zu einem Gesprächsabbruch oder einer Drohung führt. Die Person fühlt sich überfordert, nicht gehört oder provoziert.","
  - ""szenarien": ["
  - ""Streit (online oder offline)","
  - ""Hitzige Diskussionen","
  - ""Konfrontation mit einem Trigger","
  - ""Technische Frustration (z.B. im Gaming)""
  - "],"
  - ""dynamik": "Die Kommunikation verlässt die rationale Ebene und wird von Wut, Panik oder starker Frustration dominiert. Oft folgt ein TERMINATION_MARKER, um die als unerträglich empfundene Situation zu beenden ('Ich bin raus').","
  - ""beispiele": ["
  - ""Kombination aus Physiologie, Emotion und Abbruch: 'Mein Puls ist auf 180! Wenn Sie das jetzt nicht sofort klären, dann eskaliert das hier gewaltig, das garantiere ich Ihnen!'","
  - ""Wut & Abbruch: 'Alter, ich raste aus vor Wut, fühl mich komplett verarscht und jetzt reicht’s, ciao.'","
  - ""Technische Frustration: 'ALTER, DAS LAGGT SO HARD! ICH RASTE AUS! FUCK IT, ICH BIN RAUS FÜR HEUTE!'","
  - ""Angst/Panik: 'Ich krieg keine Luft mehr, alles dreht sich, ich glaube, ich kippe um, irgendwas stimmt nicht!'","
  - ""Digitale Variante: '🤬🤬🤬 ICH HASSE DAS. BIN WEG. 🚪'""
  - "],"
  - ""metamarker_kombinationen": ["
  - "{"
  - ""name": "Fight-or-Flight-Response","
  - ""kombination_mit": "TERMINATION_MARKER","
  - ""szenario": "Die Eskalation ist so hoch, dass die einzige verbleibende Handlung der sofortige Rückzug ist. Beispiel: 'Ich zittere am ganzen Körper, weil du mir schon wieder nicht zuhörst. Ich geh jetzt, bevor ich was Falsches sage!'""
  - "}"
  - "],"
  - ""semantic_grab": {"
  - ""description": "Erkennt eine hohe Dichte an Wörtern, die starke Emotionen (Wut, Zorn) und körperliche Stressreaktionen (Herzrasen, Zittern, keine Luft) beschreiben, oft in Kombination mit einem Abbruch des Gesprächs.","
  - ""patterns": ["
  - "{"
  - ""rule": "PHYSIOLOGICAL_STRESS_INDICATOR","
  - ""pattern": "Mein (Herz rast|Puls hämmert)|(ich zittere|kriege keine Luft|mein Blut kocht)","
  - ""example": "Mein Herz hämmert, ich zittere am ganzen Körper.""
  - "},"
  - "{"
  - ""rule": "PEAK_EMOTION_DECLARATION","
  - ""pattern": "(ich raste aus|ich explodiere|ich platze gleich|ich koche vor Zorn|ich kann nicht mehr)","
  - ""example": "Ich platze gleich vor Wut!""
  - "},"
  - "{"
  - ""rule": "ACCUSATION_TRIGGER","
  - ""pattern": "(weil du nicht zuhörst|du ignorierst mich|du verarschst mich|du hast null Respekt)","
  - ""example": "Du hörst mir einfach nie zu!""
  - "},"
  - "{"
  - ""rule": "COMBINED_ESCALATION_TERMINATION","
  - ""pattern": "(raste aus|reicht's jetzt|Schnauze voll) + (und ciao|ich bin raus|ich geh offline)","
  - ""example": "Jetzt reicht's, ich bin hier raus.""
  - "}"
  - "]"
  - "},"
  - ""psychologischer_hintergrund": ["
  - "{"theorie": "Polyvagal-Theorie (sympathische Mobilisierung)"},"
  - "{"abwehrmechanismus": "Affektdurchbruch, Agieren"}"
  - "]"
  - "},"
  - "{"
  - ""id": "projective_identification","
  - ""name": "PROJECTIVE_IDENTIFICATION_MARKER","
  - ""beschreibung": "Ein komplexer Abwehrmechanismus, bei dem eine Person eigene, oft unakzeptable Gefühle oder Eigenschaften nicht nur auf eine andere Person projiziert, sondern diese unbewusst dazu bringt, sich entsprechend dieser Projektion zu fühlen und zu verhalten.","
  - ""szenarien": ["
  - ""Intensive Paarbeziehungen","
  - ""Eltern-Kind-Dynamiken","
  - ""Therapeutische Beziehungen","
  - ""Toxische Arbeitsumgebungen""
  - "],"
  - ""dynamik": "Es ist ein interpersoneller Prozess. Beispiel: Person A fühlt sich innerlich inkompetent. Statt dieses Gefühl bei sich wahrzunehmen, behandelt sie Person B herablassend und kritisiert sie als inkompetent ('Kannst du gar nichts richtig machen?'). Person B fühlt sich dadurch verunsichert und fängt an, Fehler zu machen, wodurch sie sich tatsächlich inkompetent fühlt und die Projektion von Person A bestätigt.","
  - ""beispiele": ["
  - ""Projektion von Wertlosigkeit: A: 'Schon wieder die falsche Milch gekauft. Kannst du gar nichts richtig machen?' B: 'Ich hab das Gefühl, ich bin für dich nichts wert!' A: 'Siehst du? Du hast ein Problem mit deinem Selbstwert, nicht ich.'","
  - ""Projektion von Aggression: A verhält sich passiv-aggressiv. B wird wütend. A sagt: 'Ich verstehe nicht, warum du immer so ausrasten musst.'","
  - ""Projektion von Eifersucht: A kontrolliert B permanent und sagt dann: 'Deine krankhafte Eifersucht macht unsere Beziehung kaputt.'","
  - ""Projektion von Unzuverlässigkeit: 'Du bist so unzuverlässig, ich kann mich nie auf dich verlassen.'""
  - "],"
  - ""metamarker_kombinationen": [],"
  - ""semantic_grab": {"
  - ""description": "Erkennt stabile, negative 'Du-bist-so'-Zuschreibungen, die dem Gegenüber eine Eigenschaft als Wesensmerkmal unterstellen. Die KI muss den Kontext analysieren: Findet die Zuschreibung in einem Konflikt statt? Reagiert das Gegenüber, indem es die zugeschriebene Eigenschaft bestätigt?","
  - ""patterns": ["
  - "{"
  - ""rule": "NEGATIVE_TRAIT_ASSIGNMENT","
  - ""pattern": "(Du bist so|Du bist einfach|Deine) + (unzuverlässig|unordentlich|eifersüchtig|überfordert|ungeduldig|kontrollsüchtig)","
  - ""example": "Du bist einfach so ein Kontrollfreak.""
  - "},"
  - "{"
  - ""rule": "INCOMPETENCE_ACCUSATION","
  - ""pattern": "(Kannst du gar nichts richtig machen|Das hast du ja wieder toll hinbekommen|Du scheinst damit überfordert zu sein)","
  - ""example": "Das hast du ja wieder toll hinbekommen.""
  - "},"
  - "{"
  - ""rule": "EMOTIONAL_STATE_PROJECTION","
  - ""pattern": "(Warum musst du immer so ausrasten|Du bist zu sensibel|Du übertreibst total)","
  - ""example": "Warum musst du wegen jeder Kleinigkeit so ausrasten?""
  - "},"
  - "{"
  - ""rule": "BEHAVIOR_LABELING","
  - ""pattern": "(Du klammerst|Du machst immer Probleme|Du lässt mich immer allein)","
  - ""example": "Du klammerst so sehr, das macht mich fertig.""
  - "}"
  - "]"
  - "},"
  - ""psychologischer_hintergrund": ["
  - "{"theorie": "Objektbeziehungstheorie (Melanie Klein, Otto Kernberg)"},"
  - "{"abwehrmechanismus": "Projektive Identifizierung (gilt als primitiver Abwehrmechanismus)"}"
  - "]"
  - "}"
  - "]"
  - "# Beispielhafter Aufruf, um die Daten zu verwenden:"
  - "if __name__ == "__main__":"
  - "for marker in STRUKTURIERTE_MARKER_DEFINITIONEN:"
  - "print(f"--- Marker: {marker['name']} ---")"
  - "print(f"Beschreibung: {marker['beschreibung']}")"
  - "print(f"Beispiel: {marker['beispiele'][0]}")"
  - "if marker['semantic_grab']['patterns']:"
  - "print(f"Erstes semantisches Pattern ({marker['semantic_grab']['patterns'][0]['rule']}):")"
  - "print(f"  {marker['semantic_grab']['patterns'][0]['pattern']}")"
  - "print("\n" + "="*50 + "\n")"

semantic_grab:
  description: "Erkennt Muster für projective_identification_semantic_detectio.py"
  patterns:
    - rule: "AUTO_PATTERN"
      pattern: r"(muster.*wird.*ergänzt)"
tags: [neu_erstellt, needs_review]
